<?php

/**
 * Compare Webhook URLs
 *
 * This script compares the webhook URL generated by your local config
 * versus what's actually being used in production/database
 *
 * Usage: php compare_webhook_urls.php <subdomain>
 * Example: php compare_webhook_urls.php dw
 */

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Tenant;
use Illuminate\Support\Facades\DB;

// Get subdomain from command line
$subdomain = $argv[1] ?? null;

if (!$subdomain) {
    echo "❌ Error: Subdomain is required\n";
    echo "Usage: php compare_webhook_urls.php <subdomain>\n";
    echo "Example: php compare_webhook_urls.php dw\n";
    exit(1);
}

echo "\n";
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
echo "🔍 WEBHOOK URL COMPARISON\n";
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n";

// Find tenant
$tenant = Tenant::where('subdomain', $subdomain)->first();

if (!$tenant) {
    echo "❌ Tenant not found with subdomain '{$subdomain}'\n";
    exit(1);
}

echo "Tenant: {$tenant->name} (ID: {$tenant->id})\n\n";

// Get current .env configuration
$appUrl = config('app.url');
$appDomain = config('app.domain');
$protocol = parse_url($appUrl, PHP_URL_SCHEME) ?: 'https';

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
echo "📋 CURRENT .ENV CONFIGURATION\n";
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n";

echo "APP_URL: {$appUrl}\n";
echo "APP_DOMAIN: {$appDomain}\n";
echo "Protocol: {$protocol}\n\n";

// Generate webhook URL based on current config
$localWebhookUrl = "{$protocol}://{$subdomain}.{$appDomain}/api/webhook/careem/{$subdomain}";

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
echo "🔗 GENERATED WEBHOOK URLS\n";
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n";

echo "1️⃣  Based on Current .env (Subdomain-based):\n";
echo "    {$localWebhookUrl}\n\n";

// Production URLs
$productionUrls = [
    "https://{$subdomain}.madautomation.cloud/api/webhook/careem/{$subdomain}",
    "http://madautomation.cloud/api/webhook/careem/{$subdomain}",
    "http://{$appDomain}/api/webhook/careem/{$subdomain}",
];

echo "2️⃣  Expected Production URL (Subdomain-based):\n";
echo "    {$productionUrls[0]}\n\n";

echo "3️⃣  INCORRECT URL (Base domain only):\n";
echo "    {$productionUrls[1]}\n";
echo "    ❌ This would NOT work - missing subdomain!\n\n";

// Check webhook logs to see what URLs are actually being called
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
echo "📊 WEBHOOK LOGS (Last 3 requests)\n";
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n";

$logs = DB::table('webhook_logs')
    ->where('tenant_id', $tenant->id)
    ->orderBy('created_at', 'desc')
    ->limit(3)
    ->get();

if ($logs->count() > 0) {
    foreach ($logs as $log) {
        $headers = json_decode($log->headers, true);
        $host = $headers['host'][0] ?? 'Unknown';
        $scheme = isset($headers['x-forwarded-proto']) ? $headers['x-forwarded-proto'][0] : 'http';

        echo "📥 {$log->created_at} - Status: {$log->status}\n";
        echo "   Host: {$host}\n";
        echo "   Scheme: {$scheme}\n";
        echo "   Full URL: {$scheme}://{$host}/api/webhook/careem/{$subdomain}\n\n";
    }
} else {
    echo "⚠️  No webhook logs found for this tenant.\n";
    echo "   This means no webhooks have been received yet.\n\n";
}

// Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
echo "✅ WHAT TO DO\n";
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n";

$isLocal = str_contains($appDomain, 'localhost') || str_contains($appDomain, '127.0.0.1');
$correctUrl = $isLocal ? $localWebhookUrl : $productionUrls[0];

echo "✨ Configure this URL in Careem Dashboard:\n\n";
echo "   {$correctUrl}\n\n";

if ($isLocal) {
    echo "⚠️  WARNING: You're running locally!\n\n";
    echo "   For local testing with Careem webhooks:\n";
    echo "   1. Install ngrok: https://ngrok.com/\n";
    echo "   2. Run: ngrok http 8000\n";
    echo "   3. Update APP_DOMAIN in .env to ngrok domain\n";
    echo "   4. Use the ngrok URL in Careem\n\n";
} else {
    echo "📍 For Production:\n\n";
    echo "   1. Make sure your .env has:\n";
    echo "      APP_DOMAIN=madautomation.cloud\n";
    echo "      APP_URL=https://madautomation.cloud\n\n";

    echo "   2. Update Careem Dashboard with the URL above\n\n";

    echo "   3. Ensure DNS is configured:\n";
    echo "      *.madautomation.cloud → Your server IP\n";
    echo "      (This allows {$subdomain}.madautomation.cloud to work)\n\n";
}

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
echo "🔐 VERIFY CONFIGURATION\n";
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n";

echo "Run this command to test the webhook:\n\n";
echo "php test_webhook_validation.php {$subdomain}\n\n";

echo "Or visit the dashboard to copy the webhook URL:\n";
echo "https://{$subdomain}.madautomation.cloud/api-credentials\n\n";

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
